### ISSUE TITLE
About the Code Link

### ISSUE THREAD

**Issue by sh-lee-prml** [VocodexElysium/MS-SB-CQTD#1]
Thanks for nice work

The code link in https://vocodexelysium.github.io/MS-SB-CQTD/ may be wrong. 

I hope to train the model with MS-SB-CQT Discriminator. The improvement for unseen data is impressive.

Thanks

**Comment by VocodexElysium** [comment]
Dear Dr. Lee,

Thanks for your emai and your nice comments!

The code link is right, my proposed Discriminator is released as a part of Amphion (https://github.com/open-mmlab/Amphion), which is a comprehensive toolkit for audio generation. An official implementation of my paper is attached in this repo as a "starter recipe", you can just check it out (https://github.com/open-mmlab/Amphion/blob/main/egs/vocoder/gan/tfr_enhanced_hifigan/README.md).

I will also modify the demo page to make that less confusing later.

Sincerely,
Yicheng Gu
________________________________
发件人: Sang-Hoon Lee ***@***.***>
发送时间: 2023年11月28日 13:05
收件人: VocodexElysium/MS-SB-CQTD ***@***.***>
抄送: Subscribed ***@***.***>
主题: [VocodexElysium/MS-SB-CQTD] About the Code Link (Issue #1)


Thanks for nice work

The code link in https://vocodexelysium.github.io/MS-SB-CQTD/ may be wrong.

I hope to train the model with MS-SB-CQT Discriminator. The improvement for unseen data is impressive.

Thanks

―

**Comment by sh-lee-prml** [comment]
Thanks for your response! Thanks for sharing other nice projects!
